// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _predict_ensemble_HH_
#define _predict_ensemble_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "predict_ensemble_vdy.h"
#include "predict_ensemble_wdI.h"
#include "predict_ensemble_xdS.h"
#include "predict_ensemble_yd2.h"
#include "predict_ensemble_bkb.h"
#include "predict_ensemble_cud.h"
#include "predict_ensemble_dEe.h"
#include "predict_ensemble_eOg.h"
#include "predict_ensemble_fYi.h"
#include "predict_ensemble_g8j.h"
#include "predict_ensemble_hbi.h"
#include "predict_ensemble_ibs.h"
#include "predict_ensemble_jbC.h"
#include "predict_ensemble_kbM.h"
#include "predict_ensemble_lbW.h"
#include "predict_ensemble_mb6.h"
#include "predict_ensemble_ncg.h"
#include "predict_ensemble_ocq.h"
#include "predict_ensemble_pcA.h"
#include "predict_ensemble_qcK.h"
#include "predict_ensemble_rcU.h"
#include "predict_ensemble_sc4.h"
#include "predict_ensemble_tde.h"
#include "predict_ensemble_udo.h"
#include "predict_ensemble_CTRL_BUS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CTRL_BUS_ADDR_WIDTH = 4,
         unsigned int C_S_AXI_CTRL_BUS_DATA_WIDTH = 32>
struct predict_ensemble : public sc_module {
    // Port declarations 26
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > feature_stream_V_TDATA;
    sc_in< sc_logic > feature_stream_V_TVALID;
    sc_out< sc_logic > feature_stream_V_TREADY;
    sc_out< sc_lv<32> > prediction_stream_V_TDATA;
    sc_out< sc_logic > prediction_stream_V_TVALID;
    sc_in< sc_logic > prediction_stream_V_TREADY;
    sc_in< sc_logic > s_axi_CTRL_BUS_AWVALID;
    sc_out< sc_logic > s_axi_CTRL_BUS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CTRL_BUS_ADDR_WIDTH> > s_axi_CTRL_BUS_AWADDR;
    sc_in< sc_logic > s_axi_CTRL_BUS_WVALID;
    sc_out< sc_logic > s_axi_CTRL_BUS_WREADY;
    sc_in< sc_uint<C_S_AXI_CTRL_BUS_DATA_WIDTH> > s_axi_CTRL_BUS_WDATA;
    sc_in< sc_uint<C_S_AXI_CTRL_BUS_DATA_WIDTH/8> > s_axi_CTRL_BUS_WSTRB;
    sc_in< sc_logic > s_axi_CTRL_BUS_ARVALID;
    sc_out< sc_logic > s_axi_CTRL_BUS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CTRL_BUS_ADDR_WIDTH> > s_axi_CTRL_BUS_ARADDR;
    sc_out< sc_logic > s_axi_CTRL_BUS_RVALID;
    sc_in< sc_logic > s_axi_CTRL_BUS_RREADY;
    sc_out< sc_uint<C_S_AXI_CTRL_BUS_DATA_WIDTH> > s_axi_CTRL_BUS_RDATA;
    sc_out< sc_lv<2> > s_axi_CTRL_BUS_RRESP;
    sc_out< sc_logic > s_axi_CTRL_BUS_BVALID;
    sc_in< sc_logic > s_axi_CTRL_BUS_BREADY;
    sc_out< sc_lv<2> > s_axi_CTRL_BUS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<5> > ap_var_for_const1;


    // Module declarations
    predict_ensemble(sc_module_name name);
    SC_HAS_PROCESS(predict_ensemble);

    ~predict_ensemble();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    predict_ensemble_bkb* LBoostTree_is_leaf_3_U;
    predict_ensemble_cud* LBoostTree_is_leaf_0_U;
    predict_ensemble_dEe* LBoostTree_is_leaf_1_U;
    predict_ensemble_eOg* LBoostTree_is_leaf_2_U;
    predict_ensemble_fYi* LBoostTree_feature_i_U;
    predict_ensemble_g8j* LBoostTree_feature_i_3_U;
    predict_ensemble_hbi* LBoostTree_feature_i_2_U;
    predict_ensemble_ibs* LBoostTree_feature_i_1_U;
    predict_ensemble_jbC* LBoostTree_value_3_U;
    predict_ensemble_kbM* LBoostTree_value_0_U;
    predict_ensemble_lbW* LBoostTree_value_1_U;
    predict_ensemble_mb6* LBoostTree_value_2_U;
    predict_ensemble_ncg* LBoostTree_left_chil_3_U;
    predict_ensemble_ocq* LBoostTree_left_chil_2_U;
    predict_ensemble_pcA* LBoostTree_left_chil_1_U;
    predict_ensemble_qcK* LBoostTree_left_chil_U;
    predict_ensemble_rcU* LBoostTree_right_chi_3_U;
    predict_ensemble_sc4* LBoostTree_right_chi_2_U;
    predict_ensemble_tde* LBoostTree_right_chi_1_U;
    predict_ensemble_udo* LBoostTree_right_chi_U;
    predict_ensemble_CTRL_BUS_s_axi<C_S_AXI_CTRL_BUS_ADDR_WIDTH,C_S_AXI_CTRL_BUS_DATA_WIDTH>* predict_ensemble_CTRL_BUS_s_axi_U;
    predict_ensemble_vdy<1,4,32,32,32>* predict_ensemble_vdy_U1;
    predict_ensemble_wdI<1,2,32,32,1>* predict_ensemble_wdI_U2;
    predict_ensemble_xdS<1,1,8,8,8,8,32,8>* predict_ensemble_xdS_U3;
    predict_ensemble_xdS<1,1,8,8,8,8,32,8>* predict_ensemble_xdS_U4;
    predict_ensemble_yd2<1,1,32,32,32,32,32,32,32,32,32,32,32,32,32,4,32>* predict_ensemble_yd2_U5;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<14> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > feature_stream_V_0_data_out;
    sc_signal< sc_logic > feature_stream_V_0_vld_in;
    sc_signal< sc_logic > feature_stream_V_0_vld_out;
    sc_signal< sc_logic > feature_stream_V_0_ack_in;
    sc_signal< sc_logic > feature_stream_V_0_ack_out;
    sc_signal< sc_lv<32> > feature_stream_V_0_payload_A;
    sc_signal< sc_lv<32> > feature_stream_V_0_payload_B;
    sc_signal< sc_logic > feature_stream_V_0_sel_rd;
    sc_signal< sc_logic > feature_stream_V_0_sel_wr;
    sc_signal< sc_logic > feature_stream_V_0_sel;
    sc_signal< sc_logic > feature_stream_V_0_load_A;
    sc_signal< sc_logic > feature_stream_V_0_load_B;
    sc_signal< sc_lv<2> > feature_stream_V_0_state;
    sc_signal< sc_logic > feature_stream_V_0_state_cmp_full;
    sc_signal< sc_lv<32> > prediction_stream_V_1_data_out;
    sc_signal< sc_logic > prediction_stream_V_1_vld_in;
    sc_signal< sc_logic > prediction_stream_V_1_vld_out;
    sc_signal< sc_logic > prediction_stream_V_1_ack_in;
    sc_signal< sc_logic > prediction_stream_V_1_ack_out;
    sc_signal< sc_lv<32> > prediction_stream_V_1_payload_A;
    sc_signal< sc_lv<32> > prediction_stream_V_1_payload_B;
    sc_signal< sc_logic > prediction_stream_V_1_sel_rd;
    sc_signal< sc_logic > prediction_stream_V_1_sel_wr;
    sc_signal< sc_logic > prediction_stream_V_1_sel;
    sc_signal< sc_logic > prediction_stream_V_1_load_A;
    sc_signal< sc_logic > prediction_stream_V_1_load_B;
    sc_signal< sc_lv<2> > prediction_stream_V_1_state;
    sc_signal< sc_logic > prediction_stream_V_1_state_cmp_full;
    sc_signal< sc_lv<12> > LBoostTree_is_leaf_3_address0;
    sc_signal< sc_logic > LBoostTree_is_leaf_3_ce0;
    sc_signal< sc_lv<1> > LBoostTree_is_leaf_3_q0;
    sc_signal< sc_lv<12> > LBoostTree_is_leaf_0_address0;
    sc_signal< sc_logic > LBoostTree_is_leaf_0_ce0;
    sc_signal< sc_lv<1> > LBoostTree_is_leaf_0_q0;
    sc_signal< sc_lv<12> > LBoostTree_is_leaf_1_address0;
    sc_signal< sc_logic > LBoostTree_is_leaf_1_ce0;
    sc_signal< sc_lv<1> > LBoostTree_is_leaf_1_q0;
    sc_signal< sc_lv<12> > LBoostTree_is_leaf_2_address0;
    sc_signal< sc_logic > LBoostTree_is_leaf_2_ce0;
    sc_signal< sc_lv<1> > LBoostTree_is_leaf_2_q0;
    sc_signal< sc_lv<12> > LBoostTree_feature_i_address0;
    sc_signal< sc_logic > LBoostTree_feature_i_ce0;
    sc_signal< sc_lv<4> > LBoostTree_feature_i_q0;
    sc_signal< sc_lv<12> > LBoostTree_feature_i_3_address0;
    sc_signal< sc_logic > LBoostTree_feature_i_3_ce0;
    sc_signal< sc_lv<4> > LBoostTree_feature_i_3_q0;
    sc_signal< sc_lv<12> > LBoostTree_feature_i_2_address0;
    sc_signal< sc_logic > LBoostTree_feature_i_2_ce0;
    sc_signal< sc_lv<4> > LBoostTree_feature_i_2_q0;
    sc_signal< sc_lv<12> > LBoostTree_feature_i_1_address0;
    sc_signal< sc_logic > LBoostTree_feature_i_1_ce0;
    sc_signal< sc_lv<4> > LBoostTree_feature_i_1_q0;
    sc_signal< sc_lv<12> > LBoostTree_value_3_address0;
    sc_signal< sc_logic > LBoostTree_value_3_ce0;
    sc_signal< sc_lv<32> > LBoostTree_value_3_q0;
    sc_signal< sc_lv<12> > LBoostTree_value_0_address0;
    sc_signal< sc_logic > LBoostTree_value_0_ce0;
    sc_signal< sc_lv<32> > LBoostTree_value_0_q0;
    sc_signal< sc_lv<12> > LBoostTree_value_1_address0;
    sc_signal< sc_logic > LBoostTree_value_1_ce0;
    sc_signal< sc_lv<32> > LBoostTree_value_1_q0;
    sc_signal< sc_lv<12> > LBoostTree_value_2_address0;
    sc_signal< sc_logic > LBoostTree_value_2_ce0;
    sc_signal< sc_lv<32> > LBoostTree_value_2_q0;
    sc_signal< sc_lv<12> > LBoostTree_left_chil_3_address0;
    sc_signal< sc_logic > LBoostTree_left_chil_3_ce0;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_3_q0;
    sc_signal< sc_lv<12> > LBoostTree_left_chil_2_address0;
    sc_signal< sc_logic > LBoostTree_left_chil_2_ce0;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_2_q0;
    sc_signal< sc_lv<12> > LBoostTree_left_chil_1_address0;
    sc_signal< sc_logic > LBoostTree_left_chil_1_ce0;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_1_q0;
    sc_signal< sc_lv<12> > LBoostTree_left_chil_address0;
    sc_signal< sc_logic > LBoostTree_left_chil_ce0;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_q0;
    sc_signal< sc_lv<12> > LBoostTree_right_chi_3_address0;
    sc_signal< sc_logic > LBoostTree_right_chi_3_ce0;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_3_q0;
    sc_signal< sc_lv<12> > LBoostTree_right_chi_2_address0;
    sc_signal< sc_logic > LBoostTree_right_chi_2_ce0;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_2_q0;
    sc_signal< sc_lv<12> > LBoostTree_right_chi_1_address0;
    sc_signal< sc_logic > LBoostTree_right_chi_1_ce0;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_1_q0;
    sc_signal< sc_lv<12> > LBoostTree_right_chi_address0;
    sc_signal< sc_logic > LBoostTree_right_chi_ce0;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_q0;
    sc_signal< sc_logic > feature_stream_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln20_fu_566_p2;
    sc_signal< sc_logic > prediction_stream_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln27_fu_648_p2;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<8> > curren_0_reg_525;
    sc_signal< sc_lv<8> > depth_0_reg_536;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<4> > i_fu_572_p2;
    sc_signal< sc_lv<4> > i_reg_1093;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_lv<7> > i_1_fu_654_p2;
    sc_signal< sc_lv<7> > i_1_reg_1109;
    sc_signal< sc_lv<32> > zext_ln5_fu_680_p1;
    sc_signal< sc_lv<32> > zext_ln5_reg_1114;
    sc_signal< sc_lv<12> > mul_ln1_fu_692_p2;
    sc_signal< sc_lv<12> > mul_ln1_reg_1120;
    sc_signal< sc_lv<1> > icmp_ln13_fu_698_p2;
    sc_signal< sc_lv<1> > icmp_ln13_reg_1125;
    sc_signal< sc_lv<1> > icmp_ln13_1_fu_704_p2;
    sc_signal< sc_lv<1> > icmp_ln13_1_reg_1132;
    sc_signal< sc_lv<1> > icmp_ln13_2_fu_710_p2;
    sc_signal< sc_lv<1> > icmp_ln13_2_reg_1137;
    sc_signal< sc_lv<1> > or_ln13_fu_716_p2;
    sc_signal< sc_lv<1> > or_ln13_reg_1144;
    sc_signal< sc_lv<1> > icmp_ln30_fu_722_p2;
    sc_signal< sc_lv<1> > icmp_ln30_reg_1150;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<8> > depth_fu_728_p2;
    sc_signal< sc_lv<8> > depth_reg_1154;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<64> > zext_ln1_2_fu_743_p1;
    sc_signal< sc_lv<64> > zext_ln1_2_reg_1159;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< bool > ap_block_state6_pp0_stage1_iter0;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< sc_lv<4> > node_feature_index_V_fu_777_p3;
    sc_signal< sc_lv<4> > node_feature_index_V_reg_1267;
    sc_signal< sc_lv<32> > node_value_fu_798_p3;
    sc_signal< sc_lv<32> > node_value_reg_1272;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_8_reg_1279;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_9_reg_1284;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_10_reg_1289;
    sc_signal< sc_lv<8> > LBoostTree_left_chil_11_reg_1294;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_8_reg_1299;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_9_reg_1304;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_10_reg_1309;
    sc_signal< sc_lv<8> > LBoostTree_right_chi_11_reg_1314;
    sc_signal< sc_lv<1> > node_is_leaf_fu_819_p3;
    sc_signal< sc_lv<1> > node_is_leaf_reg_1319;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage2;
    sc_signal< bool > ap_block_state7_pp0_stage2_iter0;
    sc_signal< bool > ap_block_pp0_stage2_11001;
    sc_signal< sc_lv<8> > node_left_child_V_fu_826_p6;
    sc_signal< sc_lv<8> > node_left_child_V_reg_1323;
    sc_signal< sc_lv<8> > node_right_child_V_fu_835_p6;
    sc_signal< sc_lv<8> > node_right_child_V_reg_1328;
    sc_signal< sc_lv<32> > fval_fu_888_p15;
    sc_signal< sc_lv<1> > icmp_ln39_fu_939_p2;
    sc_signal< sc_lv<1> > icmp_ln39_reg_1338;
    sc_signal< sc_lv<1> > icmp_ln39_1_fu_945_p2;
    sc_signal< sc_lv<1> > icmp_ln39_1_reg_1343;
    sc_signal< sc_lv<8> > select_ln39_fu_1002_p3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<32> > grp_fu_547_p2;
    sc_signal< sc_lv<32> > sum_reg_1353;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< bool > ap_block_pp0_stage2_subdone;
    sc_signal< bool > ap_predicate_tran7to9_state7;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state7;
    sc_signal< sc_lv<4> > ap_phi_mux_i_0_phi_fu_507_p4;
    sc_signal< sc_lv<4> > i_0_reg_503;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<7> > i1_0_reg_514;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<8> > ap_phi_mux_curren_0_phi_fu_529_p4;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<8> > ap_phi_mux_depth_0_phi_fu_540_p4;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< sc_lv<32> > tmp_fu_174;
    sc_signal< bool > ap_block_pp0_stage2;
    sc_signal< sc_lv<32> > tmp_2_fu_178;
    sc_signal< sc_lv<32> > tmp_3_fu_182;
    sc_signal< sc_lv<32> > tmp_5_fu_186;
    sc_signal< sc_lv<32> > tmp_7_fu_190;
    sc_signal< sc_lv<32> > tmp_8_fu_194;
    sc_signal< sc_lv<32> > tmp_10_fu_198;
    sc_signal< sc_lv<32> > tmp_11_fu_202;
    sc_signal< sc_lv<32> > tmp_12_fu_206;
    sc_signal< sc_lv<32> > tmp_13_fu_210;
    sc_signal< sc_lv<32> > tmp_14_fu_214;
    sc_signal< sc_lv<32> > tmp_15_fu_218;
    sc_signal< sc_lv<32> > tmp_16_fu_222;
    sc_signal< sc_lv<32> > tmp_17_fu_226;
    sc_signal< sc_lv<3> > lshr_ln5_fu_660_p4;
    sc_signal< sc_lv<4> > trunc_ln1_fu_684_p1;
    sc_signal< sc_lv<4> > mul_ln1_fu_692_p1;
    sc_signal< sc_lv<2> > trunc_ln5_1_fu_670_p4;
    sc_signal< sc_lv<12> > zext_ln1_1_fu_734_p1;
    sc_signal< sc_lv<12> > add_ln1_fu_738_p2;
    sc_signal< sc_lv<4> > select_ln13_3_fu_763_p3;
    sc_signal< sc_lv<4> > select_ln13_4_fu_770_p3;
    sc_signal< sc_lv<32> > select_ln13_6_fu_784_p3;
    sc_signal< sc_lv<32> > select_ln13_7_fu_791_p3;
    sc_signal< sc_lv<1> > select_ln13_fu_805_p3;
    sc_signal< sc_lv<1> > select_ln13_1_fu_812_p3;
    sc_signal< sc_lv<4> > fval_fu_888_p14;
    sc_signal< sc_lv<32> > bitcast_ln39_fu_921_p1;
    sc_signal< sc_lv<8> > tmp_9_fu_925_p4;
    sc_signal< sc_lv<23> > trunc_ln39_fu_935_p1;
    sc_signal< sc_lv<32> > bitcast_ln39_1_fu_951_p1;
    sc_signal< sc_lv<8> > tmp_s_fu_954_p4;
    sc_signal< sc_lv<23> > trunc_ln39_1_fu_964_p1;
    sc_signal< sc_lv<1> > icmp_ln39_3_fu_978_p2;
    sc_signal< sc_lv<1> > icmp_ln39_2_fu_972_p2;
    sc_signal< sc_lv<1> > or_ln39_fu_968_p2;
    sc_signal< sc_lv<1> > or_ln39_1_fu_984_p2;
    sc_signal< sc_lv<1> > and_ln39_fu_990_p2;
    sc_signal< sc_lv<1> > grp_fu_551_p2;
    sc_signal< sc_lv<1> > and_ln39_1_fu_996_p2;
    sc_signal< bool > ap_block_pp0_stage2_00001;
    sc_signal< bool > ap_block_state15;
    sc_signal< sc_lv<14> > ap_NS_fsm;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_lv<12> > mul_ln1_fu_692_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<14> ap_ST_fsm_state1;
    static const sc_lv<14> ap_ST_fsm_state2;
    static const sc_lv<14> ap_ST_fsm_state3;
    static const sc_lv<14> ap_ST_fsm_state4;
    static const sc_lv<14> ap_ST_fsm_pp0_stage0;
    static const sc_lv<14> ap_ST_fsm_pp0_stage1;
    static const sc_lv<14> ap_ST_fsm_pp0_stage2;
    static const sc_lv<14> ap_ST_fsm_state9;
    static const sc_lv<14> ap_ST_fsm_state10;
    static const sc_lv<14> ap_ST_fsm_state11;
    static const sc_lv<14> ap_ST_fsm_state12;
    static const sc_lv<14> ap_ST_fsm_state13;
    static const sc_lv<14> ap_ST_fsm_state14;
    static const sc_lv<14> ap_ST_fsm_state15;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_D;
    static const int C_S_AXI_DATA_WIDTH;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_B;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_E;
    static const sc_lv<4> ap_const_lv4_D;
    static const sc_lv<4> ap_const_lv4_C;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<12> ap_const_lv12_C4;
    static const sc_lv<8> ap_const_lv8_C4;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<5> ap_const_lv5_5;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_LBoostTree_feature_i_1_address0();
    void thread_LBoostTree_feature_i_1_ce0();
    void thread_LBoostTree_feature_i_2_address0();
    void thread_LBoostTree_feature_i_2_ce0();
    void thread_LBoostTree_feature_i_3_address0();
    void thread_LBoostTree_feature_i_3_ce0();
    void thread_LBoostTree_feature_i_address0();
    void thread_LBoostTree_feature_i_ce0();
    void thread_LBoostTree_is_leaf_0_address0();
    void thread_LBoostTree_is_leaf_0_ce0();
    void thread_LBoostTree_is_leaf_1_address0();
    void thread_LBoostTree_is_leaf_1_ce0();
    void thread_LBoostTree_is_leaf_2_address0();
    void thread_LBoostTree_is_leaf_2_ce0();
    void thread_LBoostTree_is_leaf_3_address0();
    void thread_LBoostTree_is_leaf_3_ce0();
    void thread_LBoostTree_left_chil_1_address0();
    void thread_LBoostTree_left_chil_1_ce0();
    void thread_LBoostTree_left_chil_2_address0();
    void thread_LBoostTree_left_chil_2_ce0();
    void thread_LBoostTree_left_chil_3_address0();
    void thread_LBoostTree_left_chil_3_ce0();
    void thread_LBoostTree_left_chil_address0();
    void thread_LBoostTree_left_chil_ce0();
    void thread_LBoostTree_right_chi_1_address0();
    void thread_LBoostTree_right_chi_1_ce0();
    void thread_LBoostTree_right_chi_2_address0();
    void thread_LBoostTree_right_chi_2_ce0();
    void thread_LBoostTree_right_chi_3_address0();
    void thread_LBoostTree_right_chi_3_ce0();
    void thread_LBoostTree_right_chi_address0();
    void thread_LBoostTree_right_chi_ce0();
    void thread_LBoostTree_value_0_address0();
    void thread_LBoostTree_value_0_ce0();
    void thread_LBoostTree_value_1_address0();
    void thread_LBoostTree_value_1_ce0();
    void thread_LBoostTree_value_2_address0();
    void thread_LBoostTree_value_2_ce0();
    void thread_LBoostTree_value_3_address0();
    void thread_LBoostTree_value_3_ce0();
    void thread_add_ln1_fu_738_p2();
    void thread_and_ln39_1_fu_996_p2();
    void thread_and_ln39_fu_990_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_pp0_stage2();
    void thread_ap_block_pp0_stage2_00001();
    void thread_ap_block_pp0_stage2_11001();
    void thread_ap_block_pp0_stage2_subdone();
    void thread_ap_block_state15();
    void thread_ap_block_state2();
    void thread_ap_block_state4_io();
    void thread_ap_block_state5_pp0_stage0_iter0();
    void thread_ap_block_state6_pp0_stage1_iter0();
    void thread_ap_block_state7_pp0_stage2_iter0();
    void thread_ap_block_state8_pp0_stage0_iter1();
    void thread_ap_condition_pp0_exit_iter0_state7();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_curren_0_phi_fu_529_p4();
    void thread_ap_phi_mux_depth_0_phi_fu_540_p4();
    void thread_ap_phi_mux_i_0_phi_fu_507_p4();
    void thread_ap_predicate_tran7to9_state7();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_bitcast_ln39_1_fu_951_p1();
    void thread_bitcast_ln39_fu_921_p1();
    void thread_depth_fu_728_p2();
    void thread_feature_stream_V_0_ack_in();
    void thread_feature_stream_V_0_ack_out();
    void thread_feature_stream_V_0_data_out();
    void thread_feature_stream_V_0_load_A();
    void thread_feature_stream_V_0_load_B();
    void thread_feature_stream_V_0_sel();
    void thread_feature_stream_V_0_state_cmp_full();
    void thread_feature_stream_V_0_vld_in();
    void thread_feature_stream_V_0_vld_out();
    void thread_feature_stream_V_TDATA_blk_n();
    void thread_feature_stream_V_TREADY();
    void thread_fval_fu_888_p14();
    void thread_i_1_fu_654_p2();
    void thread_i_fu_572_p2();
    void thread_icmp_ln13_1_fu_704_p2();
    void thread_icmp_ln13_2_fu_710_p2();
    void thread_icmp_ln13_fu_698_p2();
    void thread_icmp_ln20_fu_566_p2();
    void thread_icmp_ln27_fu_648_p2();
    void thread_icmp_ln30_fu_722_p2();
    void thread_icmp_ln39_1_fu_945_p2();
    void thread_icmp_ln39_2_fu_972_p2();
    void thread_icmp_ln39_3_fu_978_p2();
    void thread_icmp_ln39_fu_939_p2();
    void thread_lshr_ln5_fu_660_p4();
    void thread_mul_ln1_fu_692_p1();
    void thread_mul_ln1_fu_692_p10();
    void thread_mul_ln1_fu_692_p2();
    void thread_node_feature_index_V_fu_777_p3();
    void thread_node_is_leaf_fu_819_p3();
    void thread_node_value_fu_798_p3();
    void thread_or_ln13_fu_716_p2();
    void thread_or_ln39_1_fu_984_p2();
    void thread_or_ln39_fu_968_p2();
    void thread_prediction_stream_V_1_ack_in();
    void thread_prediction_stream_V_1_ack_out();
    void thread_prediction_stream_V_1_data_out();
    void thread_prediction_stream_V_1_load_A();
    void thread_prediction_stream_V_1_load_B();
    void thread_prediction_stream_V_1_sel();
    void thread_prediction_stream_V_1_state_cmp_full();
    void thread_prediction_stream_V_1_vld_in();
    void thread_prediction_stream_V_1_vld_out();
    void thread_prediction_stream_V_TDATA();
    void thread_prediction_stream_V_TDATA_blk_n();
    void thread_prediction_stream_V_TVALID();
    void thread_select_ln13_1_fu_812_p3();
    void thread_select_ln13_3_fu_763_p3();
    void thread_select_ln13_4_fu_770_p3();
    void thread_select_ln13_6_fu_784_p3();
    void thread_select_ln13_7_fu_791_p3();
    void thread_select_ln13_fu_805_p3();
    void thread_select_ln39_fu_1002_p3();
    void thread_tmp_9_fu_925_p4();
    void thread_tmp_s_fu_954_p4();
    void thread_trunc_ln1_fu_684_p1();
    void thread_trunc_ln39_1_fu_964_p1();
    void thread_trunc_ln39_fu_935_p1();
    void thread_trunc_ln5_1_fu_670_p4();
    void thread_zext_ln1_1_fu_734_p1();
    void thread_zext_ln1_2_fu_743_p1();
    void thread_zext_ln5_fu_680_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
